// RootLayout.js
import { Inter, Michroma } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Form from "./components/Form";
import { Lexend_Deca, Lexend, Lexend_Zetta, Jost } from "next/font/google";
import Hero from "./containers/Hero";
import Slider from "./components/Slider";
import Portfolio from "./containers/Portfolio"
import Footer from "./containers/Footer";
import Cardlocas from "./containers/Cardlocas"
import SimpleSlider from "./components/Sliderserv";
import Sliderservtitu from "./components/Sliderservtitu";
import Slidertestimonio from "./components/Slidertestimonio";
import Header2 from "./components/Header2";
import Sobremi from "./components/Sobremi";



const inter = Inter({ subsets: ["latin"] });
const lexendD = Lexend_Deca({ subsets: ["latin"] });
const lexend = Lexend({ subsets: ["latin"] });
const lexendZ = Lexend_Zetta({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"] });
// const microma = Michroma({subsets:["latin"]})

export const metadata = {
  title: "Andrés Borrego SD",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className={jost.className}>
        <Header2></Header2>
        <Hero>

          
        </Hero>
        <Slider />
        <Portfolio />
        <Footer></Footer>
        {/* {children} */}
        

      </body>
    </html>
  );
}
